version: '3'
services:
  artbingo-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: artbingo-mysql
    image: artbingo-mysql
    command: [
            '--character-set-server=utf8',
            '--collation-server=utf8_unicode_ci'
    ]
    ports:
      - 3306:3306
