version: '3'
services:
  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    volumes:
      - ./config:/conf
      - ./data:/data
      - ./logs:/datalog
    ports: 
      - "2181:2181"