version: "3"

volumes:
  mysql_data:

services:
  mysql5.7:
    image: mysql:5.7
    container_name: mysql_5.7
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    oom_kill_disable: true
    mem_limit: 2g
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]