version: '3'
 
services:
  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - ./redis.conf:/etc/redis/redis.conf:rw
      - ./data:/data:rw
    command: redis-server /etc/redis/redis.conf
    privileged: true
